customhost = "database-1.cvgpn3fwgf5n.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "soozhenyang-employee"
customregion = "us-east-1"
